### PR TITLE
Add ESLint Support

### PR DESCRIPTION
**Pull request by zperrault**
This adds an eslint parser to work specifically with eslint's [compact format](http://eslint.org/docs/user-guide/formatters/#compact).

I modeled this after the mypy parser.

### CODE REVIEW

**Comment by rowillia** [comment]
Thanks for the PR @zperrault!  I just added this to the contributing section, but do you mind signing our CLA?  You can find instructions at https://github.com/lyft/CLA, it's super easy.

**Comment by zperrault** [comment]
@rowillia No problem! I have another PR out to sign that document right here: https://github.com/lyft/CLA/pull/9

**Comment by rowillia** [comment]
@zperrault sweet, reviewing now (sorry I've been so sporadic, just had a new baby :baby:!)

**Comment by zperrault** [comment]
@rowillia Oh no worries! Congrats!!

**Comment by zperrault** [comment]
@rowillia Any news on this?

**Comment by nmartin413** [comment]
+1

**Comment by zperrault** [comment]
Been a few months. Any updates here? @rowillia

**Comment by zperrault** [comment]
Just closing this out...

**Pull request closed without merging**
